/** Shared demo fixture for marketing screenshots — not production data */
export const DEMO_TOURNAMENT = {
  name: "WEC 2026 Panama",
  eventDate: "26 October 2026",
  venue: "Café Unido",
  location: "Panama City, Panama",
  roasterSponsor: "Café Unido",
  status: "live" as const,
  scoringVersion: "v3",
};

export const DEMO_COMPETITORS = [
  { id: 1, seed: 1, displayName: "Maya Chen", country: "Taiwan", status: "active" },
  { id: 2, seed: 2, displayName: "Luca Bianchi", country: "Italy", status: "active" },
  { id: 3, seed: 3, displayName: "Sofia Reyes", country: "Colombia", status: "active" },
  { id: 4, seed: 4, displayName: "Hiro Tanaka", country: "Japan", status: "eliminated" },
  { id: 5, seed: 5, displayName: "Amara Okonkwo", country: "Nigeria", status: "active" },
  { id: 6, seed: 6, displayName: "Jonas Berg", country: "Sweden", status: "eliminated" },
  { id: 7, seed: 7, displayName: "Elena Petrova", country: "Greece", status: "active" },
  { id: 8, seed: 8, displayName: "Mateo Silva", country: "Brazil", status: "eliminated" },
  { id: 9, seed: 9, displayName: "Priya Nair", country: "India", status: "active" },
  { id: 10, seed: 10, displayName: "Noah Williams", country: "Australia", status: "eliminated" },
  { id: 11, seed: 11, displayName: "Yuki Sato", country: "Japan", status: "active" },
  { id: 12, seed: 12, displayName: "Camille Dubois", country: "France", status: "eliminated" },
  { id: 13, seed: 13, displayName: "Diego Morales", country: "Panama", status: "active" },
  { id: 14, seed: 14, displayName: "Anna Kowalski", country: "Poland", status: "eliminated" },
  { id: 15, seed: 15, displayName: "James Park", country: "Korea", status: "active" },
  { id: 16, seed: 16, displayName: "Isla Thompson", country: "UK", status: "eliminated" },
] as const;

export const DEMO_MATCHES = [
  {
    id: 101,
    round: 3,
    matchNumber: 1,
    status: "in_progress" as const,
    competitorA: { displayName: "Maya Chen", country: "Taiwan" },
    competitorB: { displayName: "Sofia Reyes", country: "Colombia" },
    competitorAId: 1,
    competitorBId: 3,
    winnerId: null as number | null,
    scoreA: null as number | null,
    scoreB: null as number | null,
    ballotCount: 2,
  },
  {
    id: 102,
    round: 3,
    matchNumber: 2,
    status: "ready" as const,
    competitorA: { displayName: "Amara Okonkwo", country: "Nigeria" },
    competitorB: { displayName: "Elena Petrova", country: "Greece" },
    competitorAId: 5,
    competitorBId: 7,
    winnerId: null as number | null,
    scoreA: null as number | null,
    scoreB: null as number | null,
    ballotCount: 0,
  },
  {
    id: 103,
    round: 3,
    matchNumber: 3,
    status: "completed" as const,
    competitorA: { displayName: "Priya Nair", country: "India" },
    competitorB: { displayName: "Yuki Sato", country: "Japan" },
    competitorAId: 9,
    competitorBId: 11,
    winnerId: 11,
    scoreA: 41,
    scoreB: 58,
    ballotCount: 3,
  },
  {
    id: 104,
    round: 3,
    matchNumber: 4,
    status: "completed" as const,
    competitorA: { displayName: "Diego Morales", country: "Panama" },
    competitorB: { displayName: "James Park", country: "Korea" },
    competitorAId: 13,
    competitorBId: 15,
    winnerId: 13,
    scoreA: 66,
    scoreB: 33,
    ballotCount: 3,
  },
  {
    id: 90,
    round: 2,
    matchNumber: 1,
    status: "completed" as const,
    competitorA: { displayName: "Maya Chen", country: "Taiwan" },
    competitorB: { displayName: "Noah Williams", country: "Australia" },
    competitorAId: 1,
    competitorBId: 10,
    winnerId: 1,
    scoreA: 75,
    scoreB: 24,
    ballotCount: 3,
  },
  {
    id: 91,
    round: 2,
    matchNumber: 2,
    status: "completed" as const,
    competitorA: { displayName: "Sofia Reyes", country: "Colombia" },
    competitorB: { displayName: "Mateo Silva", country: "Brazil" },
    competitorAId: 3,
    competitorBId: 8,
    winnerId: 3,
    scoreA: 58,
    scoreB: 41,
    ballotCount: 3,
  },
];
